### ISSUE TITLE
not compatible with the new bloc_test: ^5.1.0

### ISSUE THREAD

**Issue by ayushin** [klisiewicz/flutter-bloc-patterns#20]
bloc_test: ^5.1.0 is required for bloc: ^4.0.0 and the `flutter test` fails on a number of tests after the upgrade

**Comment by klisiewicz** [comment]
Hello @ayushin, I'm planning a new release that is compatible with the latest version of the `flutter_bloc` library.

**Comment by klisiewicz** [comment]
Resolved in release 0.7.0.
